// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlozhlomfaonkrvrdnqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhsb3pobG9tZmFvbmtydnJkbnF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMTY5MTksImV4cCI6MjA1ODU5MjkxOX0.MN8Eq-gjBT_lt6uDx586-1qGruyUGwXBuyjm0HfcsXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);